import { TestimonialItem } from "@/types";

export const googleReviews: TestimonialItem[] = [
  {
    id: "g-rev-1",
    patientName: "K.Vijaya lakshmi",
    treatment: "Gentle Pain Relief & Clinical Assessment",
    rating: 5,
    review: "Very professional and kind treatment. Doctor diagnosed the issue accurately and provided gentle, effective therapy. Felt immediate comfort right from the initial sessions.",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 1,
    source: "google",
    reviewDate: "1 week ago",
    createdAt: "2026-03-01T10:00:00.000Z",
  },
  {
    id: "g-rev-2",
    patientName: "Hari Krishnan",
    treatment: "Musculoskeletal Pain Relief",
    rating: 5,
    review: "Dr and staff are friendly.. Understands the problem and give the required therapies... Very patient listeners who take time to explain each rehabilitation step.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 2,
    source: "google",
    reviewDate: "2 weeks ago",
    createdAt: "2026-02-23T10:00:00.000Z",
  },
  {
    id: "g-rev-3",
    patientName: "Priadarsini Vanniarajan",
    treatment: "Cervical Spine & Neck Stiffness",
    rating: 5,
    review: "After visiting this place, neck pain n stiffness reduced significantly for my husband and sundaravalli mam explained the exercises and posture corrections clearly. Great relief!",
    location: "OMR, Chennai",
    featured: true,
    published: true,
    displayOrder: 3,
    source: "google",
    reviewDate: "3 weeks ago",
    createdAt: "2026-02-16T10:00:00.000Z",
  },
  {
    id: "g-rev-4",
    patientName: "Vivek Kumar",
    treatment: "General Physiotherapy & Rehabilitation",
    rating: 5,
    review: "Dr Sundaravalli is well experienced and down to earth. The treatment and therapy are genuine and one of the best in area. Highly recommended for anyone in pain.",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 4,
    source: "google",
    reviewDate: "5 weeks ago",
    createdAt: "2026-02-02T10:00:00.000Z",
  },
  {
    id: "g-rev-5",
    patientName: "Jayamala",
    treatment: "Joint Mobilization & Pain Care",
    rating: 5,
    review: "Wonderful treatment and very friendly atmosphere. Highly recommend Dr. Sundaravalli for any joint, neck, or back issues. Very caring environment.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 5,
    source: "google",
    reviewDate: "6 weeks ago",
    createdAt: "2026-01-26T10:00:00.000Z",
  },
  {
    id: "g-rev-6",
    patientName: "Fakrudeen Ali T",
    treatment: "Clinical Orthopedic Care",
    rating: 5,
    review: "Excellent physiotherapy clinic in Perungudi. Well equipped center with dedicated therapy rooms and very courteous, patient doctor. Five stars!",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 6,
    source: "google",
    reviewDate: "9 weeks ago",
    createdAt: "2026-01-05T10:00:00.000Z",
  },
  {
    id: "g-rev-7",
    patientName: "606",
    treatment: "Root-Cause Pain Management",
    rating: 5,
    review: "Best place for pain relief. The doctor takes time to understand the root cause and treats thoroughly with patience instead of temporary shortcuts.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 7,
    source: "google",
    reviewDate: "11 weeks ago",
    createdAt: "2025-12-22T10:00:00.000Z",
  },
  {
    id: "g-rev-8",
    patientName: "Rekha Mukundan",
    treatment: "Orthopedic Rehabilitation & Joint Care",
    rating: 5,
    review: "Most reliable very patient doctor. Knowledgeable doctor who listens carefully to symptoms and delivers focused, evidence-based therapy sessions.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 8,
    source: "google",
    reviewDate: "13 weeks ago",
    createdAt: "2025-12-08T10:00:00.000Z",
  },
  {
    id: "g-rev-9",
    patientName: "Anuradha Parakkat",
    treatment: "Pain Management & Relief",
    rating: 5,
    review: "Gentle and very nice. Thank you so much for the caring therapy sessions. Made a big difference in my mobility.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 9,
    source: "google",
    reviewDate: "21 weeks ago",
    createdAt: "2025-10-13T10:00:00.000Z",
  },
  {
    id: "g-rev-10",
    patientName: "suriya maha",
    treatment: "Shockwave Therapy & Super Speciality Rehab",
    rating: 5,
    review: "Super speciality physiotherapy centre. Well equipped center with an advanced setup. Shockwave therapy, which is only available in super speciality physiotherapy centres, is provided here with utmost precision.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 10,
    source: "google",
    reviewDate: "22 weeks ago",
    createdAt: "2025-10-06T10:00:00.000Z",
  },
  {
    id: "g-rev-11",
    patientName: "Richa Sekar",
    treatment: "Physical Rehabilitation & Posture Guidance",
    rating: 5,
    review: "Great experience with Dr. Sundaravalli. She explains the therapy process well and ensures complete relief. High quality equipment and serene clinic.",
    location: "Perungudi, Chennai",
    featured: false,
    published: true,
    displayOrder: 11,
    source: "google",
    reviewDate: "22 weeks ago",
    createdAt: "2025-10-06T10:00:00.000Z",
  },
  {
    id: "g-rev-12",
    patientName: "ajaykumar Pandian",
    treatment: "Joint Mobilization & Clinical Physio",
    rating: 5,
    review: "One of the best physiotherapists I’ve ever come across. This is my honest experience. Exceptional clinical acumen, ethical practice, and genuine care for patients.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 12,
    source: "google",
    reviewDate: "23 weeks ago",
    createdAt: "2025-09-29T10:00:00.000Z",
  },
  {
    id: "g-rev-13",
    patientName: "Anjali Lakshmi",
    treatment: "Lifestyle & Postural Discomfort Management",
    rating: 5,
    review: "Very good physiotherapy clinic. They clearly explain what they are doing, the probable cause of the pain, and provide helpful suggestions on diet and lifestyle to reduce discomfort.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 13,
    source: "google",
    reviewDate: "33 weeks ago",
    createdAt: "2025-07-21T10:00:00.000Z",
  },
  {
    id: "g-rev-14",
    patientName: "s.syed jaffer sadiq",
    treatment: "Electrotherapy & Modal Therapy",
    rating: 5,
    review: "Thank you Dr. Sundaravalli and their assistants. Proper equipment’s used for physio and required advice given to make sure the treatment goes well.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 14,
    source: "google",
    reviewDate: "35 weeks ago",
    createdAt: "2025-07-07T10:00:00.000Z",
  },
  {
    id: "g-rev-15",
    patientName: "Deon Rozario",
    treatment: "Joint Stiffness & Flexibility Recovery",
    rating: 5,
    review: "Very reliable and experienced physiotherapist. Treatment was extremely effective for my stiffness and joint mobility. Friendly and attentive staff.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 15,
    source: "google",
    reviewDate: "36 weeks ago",
    createdAt: "2025-06-30T10:00:00.000Z",
  },
  {
    id: "g-rev-16",
    patientName: "Elakkia Jacob",
    treatment: "Severe Lower Back & Radiating Leg Pain",
    rating: 5,
    review: "I had severe back pain and leg pain, and I couldn’t even stand for two seconds. After taking treatment here, I was able to stand, walk, and resume daily activities without agony. Immensely thankful to Dr. Sundaravalli!",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 16,
    source: "google",
    reviewDate: "38 weeks ago",
    createdAt: "2025-06-16T10:00:00.000Z",
  },
  {
    id: "g-rev-17",
    patientName: "kiruba shankar",
    treatment: "Musculoskeletal Pain Recovery",
    rating: 5,
    review: "Exceptional service and caring treatment. Dr. Sundaravalli is very knowledgeable and treats each patient with customized attention.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 17,
    source: "google",
    reviewDate: "40 weeks ago",
    createdAt: "2025-06-02T10:00:00.000Z",
  },
  {
    id: "g-rev-18",
    patientName: "Gokul Ganesh",
    treatment: "Lumbar Spine & Muscle Spasm (7 Sessions)",
    rating: 5,
    review: "I had severe pain in my back and leg muscles, so I visited this clinic for treatment. The doctor suggested 7 sessions. By the 7th session, the pain completely vanished and strength was fully restored.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 18,
    source: "google",
    reviewDate: "42 weeks ago",
    createdAt: "2025-05-19T10:00:00.000Z",
  },
  {
    id: "g-rev-19",
    patientName: "Sathyanarayanan O",
    treatment: "1-Month Stiff Neck & Cervical Relief",
    rating: 5,
    review: "Had a very stiff neck for almost a month, came to Dr Sundravalli just for a week and the pain has vanished. Over the week the treatment and targeted exercises gave dramatic, lasting relief.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 19,
    source: "google",
    reviewDate: "42 weeks ago",
    createdAt: "2025-05-19T10:00:00.000Z",
  },
  {
    id: "g-rev-20",
    patientName: "Jerrin John",
    treatment: "Targeted Musculoskeletal Therapy",
    rating: 5,
    review: "Doctor understands our needs and do the treatment accordingly. Compassionate and very well trained. Recommended place for anyone dealing with persistent ache.",
    location: "OMR, Chennai",
    featured: false,
    published: true,
    displayOrder: 20,
    source: "google",
    reviewDate: "42 weeks ago",
    createdAt: "2025-05-19T10:00:00.000Z",
  },
  {
    id: "g-rev-21",
    patientName: "Subramanian Hariharan",
    treatment: "General Orthopedic Care",
    rating: 5,
    review: "Good 👍 Very effective treatment, courteous staff, and very transparent care.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 21,
    source: "google",
    reviewDate: "43 weeks ago",
    createdAt: "2025-05-12T10:00:00.000Z",
  },
  {
    id: "g-rev-22",
    patientName: "sowmya gour",
    treatment: "Ethical & Patient-Centric Physiotherapy",
    rating: 5,
    review: "I have visited GG physiotherapy couple of times and what i have observed is Dr sundaravalli is service minded and not money minded. She makes sure that the patient’s concern is addressed and pain is cured.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 22,
    source: "google",
    reviewDate: "45 weeks ago",
    createdAt: "2025-04-28T10:00:00.000Z",
  },
  {
    id: "g-rev-23",
    patientName: "Nithya Narayanan",
    treatment: "Pain Relief & Active Rehabilitation",
    rating: 5,
    review: "Excellent treatment and great care by Dr. Sundaravalli. She guides step-by-step through exercises for long-term health.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 23,
    source: "google",
    reviewDate: "47 weeks ago",
    createdAt: "2025-04-14T10:00:00.000Z",
  },
  {
    id: "g-rev-24",
    patientName: "Thulasi K",
    treatment: "Orthopedic Rehabilitation",
    rating: 5,
    review: "Super 👌 👍 😍 Highly recommend GG Physiotherapy Clinic to everyone seeking quick and reliable recovery.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 24,
    source: "google",
    reviewDate: "48 weeks ago",
    createdAt: "2025-04-07T10:00:00.000Z",
  },
  {
    id: "g-rev-25",
    patientName: "prabu mohan",
    treatment: "Years-Long Chronic Neck Pain",
    rating: 5,
    review: "Neck pain was an irritant for years which aggravated over the last few weeks, wanted to give physiotherapy a try. Dr. Sundaravalli diagnosed the root cervical issue and provided instant relief through focused therapy.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 25,
    source: "google",
    reviewDate: "49 weeks ago",
    createdAt: "2025-03-31T10:00:00.000Z",
  },
  {
    id: "g-rev-26",
    patientName: "Sarathkumar MC",
    treatment: "Sports Trauma & Muscle Strain",
    rating: 5,
    review: "Outstanding care and dedicated attention. Recovered from my sports muscle strain quickly thanks to the expert hands of the doctor.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 26,
    source: "google",
    reviewDate: "50 weeks ago",
    createdAt: "2025-03-24T10:00:00.000Z",
  },
  {
    id: "g-rev-27",
    patientName: "MUTHU KARTHICK KARTHICK",
    treatment: "Post-Stroke Neurological Rehabilitation",
    rating: 5,
    review: "Dr. sundaravalli is a best physiotherapist my friend has suffer stroke past 3month. she give best treatment and well planned neuro rehab which helped him regain his limb movements and confidence.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 27,
    source: "google",
    reviewDate: "50 weeks ago",
    createdAt: "2025-03-24T10:00:00.000Z",
  },
  {
    id: "g-rev-28",
    patientName: "sakthi pooja",
    treatment: "Long-Standing Knee Pain",
    rating: 5,
    review: "Dr.sundaravalli was very knowledgeable and high experience in physio they treat very well. I had knee pain for long days and found total cure here without invasive procedures.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 28,
    source: "google",
    reviewDate: "50 weeks ago",
    createdAt: "2025-03-24T10:00:00.000Z",
  },
  {
    id: "g-rev-29",
    patientName: "Saravanan gseva org",
    treatment: "Ultrasound & IFT / TENS for Frozen Shoulder",
    rating: 5,
    review: "I underwent two sessions totalling about 9 days and had ultra sound and IFT / Tenz treatment for my freezing movement in shoulder. Significant improvement achieved and range of motion returned.",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 29,
    source: "google",
    reviewDate: "30 Aug 2025",
    createdAt: "2025-08-30T10:00:00.000Z",
  },
  {
    id: "g-rev-30",
    patientName: "Gnanadeepak Thangavel",
    treatment: "Clinical Physiotherapy Assessment",
    rating: 5,
    review: "Great clinical facility and skilled physiotherapist in Perungudi. Clean, well equipped, and transparent approach.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 30,
    source: "google",
    reviewDate: "13 Aug 2025",
    createdAt: "2025-08-13T10:00:00.000Z",
  },
  {
    id: "g-rev-31",
    patientName: "Koushick Bhalan",
    treatment: "Affordable High-Quality Physio Care",
    rating: 5,
    review: "Good and affordable treatment. Clear advice and no unnecessary sessions pushed.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 31,
    source: "google",
    reviewDate: "25 Jul 2025",
    createdAt: "2025-07-25T10:00:00.000Z",
  },
  {
    id: "g-rev-32",
    patientName: "manjula v",
    treatment: "Pain Relief Therapy",
    rating: 5,
    review: "Very good treatment and was very effective. Thanks to Dr. Sundaravalli for her dedicated care.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 32,
    source: "google",
    reviewDate: "18 Jul 2025",
    createdAt: "2025-07-18T10:00:00.000Z",
  },
  {
    id: "g-rev-33",
    patientName: "Randhir Singh",
    treatment: "Exercise Therapy & Guidance",
    rating: 5,
    review: "Very good experience. Doctor explained every exercise and treated with patience. Clinic is clean and well maintained.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 33,
    source: "google",
    reviewDate: "18 Jul 2025",
    createdAt: "2025-07-18T10:00:00.000Z",
  },
  {
    id: "g-rev-34",
    patientName: "Neha Ramnathan",
    treatment: "Severe Hip Pain & Sciatic Nerve Pressure",
    rating: 5,
    review: "I had severe hip pain on my left leg. In spite of taking paracetamol and ibuprofen, the medications wouldn't help. The targeted physio sessions relieved the nerve pressure and cured the hip pain completely. Truly grateful!",
    location: "OMR, Chennai",
    featured: true,
    published: true,
    displayOrder: 34,
    source: "google",
    reviewDate: "12 Jul 2025",
    createdAt: "2025-07-12T10:00:00.000Z",
  },
  {
    id: "g-rev-35",
    patientName: "Renuka M.D",
    treatment: "Cervical Spondylosis & Neck Stiffness",
    rating: 5,
    review: "I visited Dr. Sundaravalli after seeing the reviews online and trusted her process in helping me out with my neck pain and stiffness. The result was remarkable, and she gave great postural exercises for work.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 35,
    source: "google",
    reviewDate: "21 Jun 2025",
    createdAt: "2025-06-21T10:00:00.000Z",
  },
  {
    id: "g-rev-36",
    patientName: "Parthasarathy V",
    treatment: "Physical Rehabilitation",
    rating: 5,
    review: "Excellent treatment 👌 Very skilled physiotherapist who knows how to address acute joint stiffness quickly.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 36,
    source: "google",
    reviewDate: "16 Jun 2025",
    createdAt: "2025-06-16T10:00:00.000Z",
  },
  {
    id: "g-rev-37",
    patientName: "Subramani Nayagam",
    treatment: "Root Cause Pain Diagnosis",
    rating: 5,
    review: "Good consultation provided by physiotherapist and identified the root cause of pain, Before I vist to clinic, I have lot of discomfort and worry, but within a few sessions my mobility improved drastically.",
    location: "Perungudi, Chennai",
    featured: false,
    published: true,
    displayOrder: 37,
    source: "google",
    reviewDate: "16 Jun 2025",
    createdAt: "2025-06-16T10:00:00.000Z",
  },
  {
    id: "g-rev-38",
    patientName: "Thangarasu P (Senthil)",
    treatment: "7-Year Chronic IT Professional Neck Pain",
    rating: 5,
    review: "I am senthil working IT Job. I have been suffering neck pain for 7 years. Usually I go to hospital and take tablets and get temporary relief. Here at GG Physio, Dr. Sundaravalli identified the posture strain and provided therapeutic sessions that finally solved my 7-year agony.",
    location: "Perungudi / OMR IT Corridor",
    featured: true,
    published: true,
    displayOrder: 38,
    source: "google",
    reviewDate: "30 Apr 2025",
    createdAt: "2025-04-30T10:00:00.000Z",
  },
  {
    id: "g-rev-39",
    patientName: "Saroja Raman",
    treatment: "Geriatric Care & Ongoing Joint Relief",
    rating: 5,
    review: "I am under treatment in GG physiotherapy clinic for last 1 year in different duration. I feel very satisfied with the treatment and getting better with the pain. Homely feeling I get in the clinic. Very warm and attentive care.",
    location: "Perungudi, Chennai",
    featured: false,
    published: true,
    displayOrder: 39,
    source: "google",
    reviewDate: "19 Apr 2025",
    createdAt: "2025-04-19T10:00:00.000Z",
  },
  {
    id: "g-rev-40",
    patientName: "ezhil arasan",
    treatment: "Ankle Stiffness & Strain (5-Day Course)",
    rating: 5,
    review: "Had a very good treatment from the Dr. Sundaravalli. It was a 5 days course for leg ankle stiffness & strain. Due to targeted stretching and electro-stimulation, I was able to walk normally without limp.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 40,
    source: "google",
    reviewDate: "10 Apr 2025",
    createdAt: "2025-04-10T10:00:00.000Z",
  },
  {
    id: "g-rev-41",
    patientName: "Lakshmi Ramasubramaniyan",
    treatment: "Targeted Healing & Home Exercise",
    rating: 5,
    review: "The physiotherapist understood my challenge and gave the right treatment that helped me heal faster. She guided me to do exercises properly at home to maintain flexibility.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 41,
    source: "google",
    reviewDate: "7 Apr 2025",
    createdAt: "2025-04-07T10:00:00.000Z",
  },
  {
    id: "g-rev-42",
    patientName: "sujy Mathew",
    treatment: "Compassionate Pain Relief",
    rating: 5,
    review: "Compassionate doctor and effective physio sessions. Thank you Dr. Sundaravalli for making recovery so seamless!",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 42,
    source: "google",
    reviewDate: "22 Mar 2025",
    createdAt: "2025-03-22T10:00:00.000Z",
  },
  {
    id: "g-rev-43",
    patientName: "T K",
    treatment: "Severe Knee Pain & Meniscus Rehabilitation",
    rating: 5,
    review: "I experienced significant knee pain and sought treatment at GG Physiotherapy. The therapist accurately diagnosed the joint inflammation and provided therapeutic exercises that brought down swelling and restored walking ability.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 43,
    source: "google",
    reviewDate: "8 Mar 2025",
    createdAt: "2025-03-08T10:00:00.000Z",
  },
  {
    id: "g-rev-44",
    patientName: "angappan shanmugam",
    treatment: "Clinical Physiotherapy",
    rating: 5,
    review: "Superb treatment. Very neat clinic, professional care, and patient approach by Dr. Sundaravalli.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 44,
    source: "google",
    reviewDate: "7 Mar 2025",
    createdAt: "2025-03-07T10:00:00.000Z",
  },
  {
    id: "g-rev-45",
    patientName: "Heera Radhakrishnan",
    treatment: "Severe Sciatica (Lower Back & Leg Pain)",
    rating: 5,
    review: "I recently sought treatment at GG Physiotherapy Clinic for severe sciatica pain (Lower back pain and leg pain). The combination of lumbar traction, gentle mobilization, and electrotherapy provided complete relief. Couldn't recommend them enough!",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 45,
    source: "google",
    reviewDate: "18 Feb 2025",
    createdAt: "2025-02-18T10:00:00.000Z",
  },
  {
    id: "g-rev-46",
    patientName: "sharmila s",
    treatment: "General Pain Care",
    rating: 5,
    review: "Wonderful care and prompt pain relief. Thank you Dr. Sundaravalli!",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 46,
    source: "google",
    reviewDate: "12 Feb 2025",
    createdAt: "2025-02-12T10:00:00.000Z",
  },
  {
    id: "g-rev-47",
    patientName: "Latha Nutan",
    treatment: "Physiotherapy Service",
    rating: 5,
    review: "Physiotherapy service is very good. Dr. Sundaravalli and assistants are very caring and helpful.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 47,
    source: "google",
    reviewDate: "11 Feb 2025",
    createdAt: "2025-02-11T10:00:00.000Z",
  },
  {
    id: "g-rev-48",
    patientName: "Keerthi Raj V",
    treatment: "Neck & Shoulder Pain Recovery",
    rating: 5,
    review: "Very knowledgeable and explains each and every problem with patience. My neck and shoulder pain is fading away after the physio sessions. I can feel that I am recovering after the treatment.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 48,
    source: "google",
    reviewDate: "13 Jan 2025",
    createdAt: "2025-01-13T10:00:00.000Z",
  },
  {
    id: "g-rev-49",
    patientName: "Chandhini V",
    treatment: "Shoulder Pain, Arm Numbness & Back Ache (7 Days)",
    rating: 5,
    review: "I visited the GG Clinic with concerns about shoulder pain, numbness, and back pain. After undergoing 7 days of treatment, the radiating numbness has completely gone and shoulder rotation is smooth.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 49,
    source: "google",
    reviewDate: "27 Dec 2024",
    createdAt: "2024-12-27T10:00:00.000Z",
  },
  {
    id: "g-rev-50",
    patientName: "Nallaiah S",
    treatment: "Severe Neck & Shoulder Pain",
    rating: 5,
    review: "I had severe neck and shoulder pain, I went for Physio treatment to GG Physiotheraphy Clinic. Sundaravalli Mam heard the issue patiently, assessed my posture, and gave systematic therapy. Very satisfied!",
    location: "Perungudi, Chennai",
    featured: false,
    published: true,
    displayOrder: 50,
    source: "google",
    reviewDate: "26 Dec 2024",
    createdAt: "2024-12-26T10:00:00.000Z",
  },
  {
    id: "g-rev-51",
    patientName: "Jayasri",
    treatment: "Back Pain Rehabilitation",
    rating: 5,
    review: "Effective physiotherapy for my back pain. Very polite and friendly doctor who creates a very comfortable environment.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 51,
    source: "google",
    reviewDate: "21 Dec 2024",
    createdAt: "2024-12-21T10:00:00.000Z",
  },
  {
    id: "g-rev-52",
    patientName: "Mohammed Imran",
    treatment: "Geriatric Right Leg Pain (5 Sittings)",
    rating: 5,
    review: "Good physiotherapy centre. I went for my mother's right leg pain , after 5 sittings the treatment gone well and she is able to walk comfortably without pain now.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 52,
    source: "google",
    reviewDate: "20 Dec 2024",
    createdAt: "2024-12-20T10:00:00.000Z",
  },
  {
    id: "g-rev-53",
    patientName: "Santhoshini Srinivasan",
    treatment: "Custom Made Equipments & Tailored Rehab",
    rating: 5,
    review: "Excellent service , custom made equipments to suit all needs and very practical doctor who understands patient constraints and provides feasible exercise regimens.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 53,
    source: "google",
    reviewDate: "17 Dec 2024",
    createdAt: "2024-12-17T10:00:00.000Z",
  },
  {
    id: "g-rev-54",
    patientName: "Arunachalam P K",
    treatment: "Top-Tier Physiotherapy",
    rating: 5,
    review: "Top quality physiotherapy clinic in Perungudi. Professional, hygienic, and highly caring.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 54,
    source: "google",
    reviewDate: "1 Dec 2024",
    createdAt: "2024-12-01T10:00:00.000Z",
  },
  {
    id: "g-rev-55",
    patientName: "Bhasker Saiteja",
    treatment: "Multi-Year Neck & Shoulder Issue",
    rating: 5,
    review: "I have been suffering from my neck and shoulder issue from past few years. But after consulting the doctor she analysed the exact posture root cause and treated it with immense skill.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 55,
    source: "google",
    reviewDate: "1 Dec 2024",
    createdAt: "2024-12-01T10:00:00.000Z",
  },
  {
    id: "g-rev-56",
    patientName: "ajay athith",
    treatment: "Personalized Care & Relief",
    rating: 5,
    review: "Very effective treatment given with personal care and focused recovery methods.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 56,
    source: "google",
    reviewDate: "25 Nov 2024",
    createdAt: "2024-11-25T10:00:00.000Z",
  },
  {
    id: "g-rev-57",
    patientName: "Kavitha Agencies",
    treatment: "Orthopedic Rehabilitation",
    rating: 5,
    review: "Very nice treatment and dedicated physiotherapy service in Perungudi.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 57,
    source: "google",
    reviewDate: "5 Nov 2024",
    createdAt: "2024-11-05T10:00:00.000Z",
  },
  {
    id: "g-rev-58",
    patientName: "vasuki k",
    treatment: "Pain Reduction & Mobility",
    rating: 5,
    review: "Doctor is very kind and patient. Pain reduced significantly after the sessions. Very thankful.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 58,
    source: "google",
    reviewDate: "14 Oct 2024",
    createdAt: "2024-10-14T10:00:00.000Z",
  },
  {
    id: "g-rev-59",
    patientName: "MURALIDARAN MACHAKANDAN",
    treatment: "Musculoskeletal Improvement",
    rating: 5,
    review: "Therapy is good and felt good improvement in my issue within a few days.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 59,
    source: "google",
    reviewDate: "3 Oct 2024",
    createdAt: "2024-10-03T10:00:00.000Z",
  },
  {
    id: "g-rev-60",
    patientName: "siva sivaprasad",
    treatment: "Back Ache Relief & Lumbar Care",
    rating: 5,
    review: "This Doctor is very calm and kind in treating their Patients. Went for my back ache and found better result. Highly recommended.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 60,
    source: "google",
    reviewDate: "25 Sept 2024",
    createdAt: "2024-09-25T10:00:00.000Z",
  },
  {
    id: "g-rev-61",
    patientName: "Y Mala",
    treatment: "Holistic & Logical Musculoskeletal Therapy",
    rating: 5,
    review: "The doctor is patient and offers logical explanation to the problem. Her method of treatment is helpful, she is also an excellent person to get to know. I personally loved her treatment.",
    location: "Perungudi, Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 61,
    source: "google",
    reviewDate: "21 Sept 2024",
    createdAt: "2024-09-21T10:00:00.000Z",
  },
  {
    id: "g-rev-62",
    patientName: "Radhakrishnan V",
    treatment: "Complete Back Pain Cure",
    rating: 5,
    review: "I have been cured from back pain completely . Expert treatment. Thanks to the Physiotherapist Dr. Sundaravalli.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 62,
    source: "google",
    reviewDate: "20 Sept 2024",
    createdAt: "2024-09-20T10:00:00.000Z",
  },
  {
    id: "g-rev-63",
    patientName: "Suresh Kumar",
    treatment: "6-Year Leg, Hip & Neck Pain (Traction & Therapy)",
    rating: 5,
    review: "I had leg pain for 6 years, hip and neck pain for past 2 years I went to GG therapy centre they given traction and targeted therapies. Huge improvement after years of chronic struggle!",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 63,
    source: "google",
    reviewDate: "12 Sept 2024",
    createdAt: "2024-09-12T10:00:00.000Z",
  },
  {
    id: "g-rev-64",
    patientName: "Rajeshwari N",
    treatment: "Incredible Care & Joint Recovery",
    rating: 5,
    review: "Very nice. Incredible service with more care and attention to every small detail.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 64,
    source: "google",
    reviewDate: "11 Sept 2024",
    createdAt: "2024-09-11T10:00:00.000Z",
  },
  {
    id: "g-rev-65",
    patientName: "Premaanand Anand",
    treatment: "Satisfying Pain Relief",
    rating: 5,
    review: "Good service and treatment is well satisfied. I am very happy to come again whenever needed.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 65,
    source: "google",
    reviewDate: "10 Sept 2024",
    createdAt: "2024-09-10T10:00:00.000Z",
  },
  {
    id: "g-rev-66",
    patientName: "Arjun Vijay",
    treatment: "Shoulder Pain Assessment & Mobilization",
    rating: 5,
    review: "Sundari madam is a very knowledgeable and experienced physiotherapist. She assesses the issue in the right way and treats it properly. I had a good experience with my shoulder pain.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 66,
    source: "google",
    reviewDate: "4 Sept 2024",
    createdAt: "2024-09-04T10:00:00.000Z",
  },
  {
    id: "g-rev-67",
    patientName: "praveen kumar",
    treatment: "Accurate Diagnosis & Positive Encouragement",
    rating: 5,
    review: "Dr. Sundaravalli mam has an extraordinary knowledge in diagnosing the problem... Along with treatment her positive words give immense confidence to recover quickly.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 67,
    source: "google",
    reviewDate: "30 Aug 2024",
    createdAt: "2024-08-30T10:00:00.000Z",
  },
  {
    id: "g-rev-68",
    patientName: "Durga devi",
    treatment: "Sciatica Nerve Decompression & Exercises",
    rating: 5,
    review: "Really doctor treated me well with proper therapy and exercise for sciatica pain. Pain radiating to leg subsided completely.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 68,
    source: "google",
    reviewDate: "22 Jul 2024",
    createdAt: "2024-07-22T10:00:00.000Z",
  },
  {
    id: "g-rev-69",
    patientName: "Navin Prasath C V",
    treatment: "Shoulder Pain & Strengthening Exercises",
    rating: 5,
    review: "Given nice treatment for shoulder pain. After treatment exercises were taught clearly for home strengthening.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 69,
    source: "google",
    reviewDate: "11 Jul 2024",
    createdAt: "2024-07-11T10:00:00.000Z",
  },
  {
    id: "g-rev-70",
    patientName: "Selva Jenner",
    treatment: "Personalized Exercise Guidance",
    rating: 5,
    review: "Excellent therapy and personalized exercise guidance. The doctor explains the mechanics thoroughly.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 70,
    source: "google",
    reviewDate: "9 Jul 2024",
    createdAt: "2024-07-09T10:00:00.000Z",
  },
  {
    id: "g-rev-71",
    patientName: "Kavitha Ramanathan",
    treatment: "Affordable & Worthy Physiotherapy",
    rating: 5,
    review: "Very good place for physio. Affordable and worthy treatment in Perungudi.",
    location: "Perungudi, Chennai",
    featured: false,
    published: true,
    displayOrder: 71,
    source: "google",
    reviewDate: "9 Jul 2024",
    createdAt: "2024-07-09T10:00:00.000Z",
  },
  {
    id: "g-rev-72",
    patientName: "Vindhya Hegde",
    treatment: "Knee Inflammation & Strengthening Exercises",
    rating: 5,
    review: "I recently took physiotherapy treatment for my knee inflammation from Dr.Sundaravalli. She was very kind, patient and very talented. She gave me good insights and taught knee strengthening exercises. I strongly recommend this clinic for anyone seeking physiotherapy. Price was affordable.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 72,
    source: "google",
    reviewDate: "5 Jul 2024",
    createdAt: "2024-07-05T10:00:00.000Z",
  },
  {
    id: "g-rev-73",
    patientName: "Senthamizhan Mohan",
    treatment: "Lower Back Pain Diagnosis & Staff Care",
    rating: 5,
    review: "I recently visited GG Physiotherapy for lower back pain, and I couldn't be more satisfied with the treatment I received. Dr. Sundaravalli Jayakumar is exceptionally knowledgeable and quickly understands my condition. She made me feel comfortable and cared for throughout the process. The supporting staff were also very helpful and attentive. Highly recommend GG Physiotherapy!",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 73,
    source: "google",
    reviewDate: "3 Jul 2024",
    createdAt: "2024-07-03T10:00:00.000Z",
  },
  {
    id: "g-rev-74",
    patientName: "usha m",
    treatment: "Comprehensive Joint Therapy",
    rating: 5,
    review: "Great care taken during each session. Doctor understands patient needs very well and adapts therapies smoothly.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 74,
    source: "google",
    reviewDate: "30 Jun 2024",
    createdAt: "2024-06-30T10:00:00.000Z",
  },
  {
    id: "g-rev-75",
    patientName: "sivapriya natesh",
    treatment: "Lumbar Disc Herniation & Spine Rehab",
    rating: 5,
    review: "I recently received physiotherapy for my lumbar disc problem from Dr. Sundara valli. She is kind and talented. Her treatment has significantly improved my condition and allowed me to return to normal routine.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 75,
    source: "google",
    reviewDate: "30 Jun 2024",
    createdAt: "2024-06-30T10:00:00.000Z",
  },
  {
    id: "g-rev-76",
    patientName: "SRIRAM R",
    treatment: "Physical Rehabilitation",
    rating: 5,
    review: "Very satisfied with the treatment. Highly recommended physiotherapy clinic for joint and muscle recovery.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 76,
    source: "google",
    reviewDate: "29 Jun 2024",
    createdAt: "2024-06-29T10:00:00.000Z",
  },
  {
    id: "g-rev-77",
    patientName: "sowmya arvind",
    treatment: "Elderly Mother Hand Mobility (15 Days)",
    rating: 5,
    review: "Myself and my mother are very happy with the therapist Mrs.Sundaravalli. we went to GG physiotherapist for my mother. My mother was not able to move her hand. After 15 days treatment she is very much better now. The therapist was very kind and gave clear explanation about the problem. My mother felt very comfortable and happy with physiotherapist 🙏",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 77,
    source: "google",
    reviewDate: "29 Jun 2024",
    createdAt: "2024-06-29T10:00:00.000Z",
  },
  {
    id: "g-rev-78",
    patientName: "Swarna lakshmi",
    treatment: "Stiff Neck & Shoulder Pain Rehabilitation",
    rating: 5,
    review: "I have gone for stiff neck and shoulder pain. The team was kind and took care in explaining to me the issue and the treatment required. Post treatment the exercises were taught to me. Great effort by the clinic and their staff. All the best to them.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 78,
    source: "google",
    reviewDate: "4 Jun 2024",
    createdAt: "2024-06-04T10:00:00.000Z",
  },
  {
    id: "g-rev-79",
    patientName: "Ramanathan Subramanian",
    treatment: "Rigid Cervical & Upper Back Strain",
    rating: 5,
    review: "This centre has got a very good physiotherapist Dr.Sundaravalli Jayakumar who is knowledgeable, fast in understanding the patient's problem and ensures a correct course of treatment. Added advantage is the kind and humane approach. I went for the rigid cervical and upper back strain and got a satisfactory treatment.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 79,
    source: "google",
    reviewDate: "4 Jun 2024",
    createdAt: "2024-06-04T10:00:00.000Z",
  },
  {
    id: "g-rev-80",
    patientName: "Subha Kathir",
    treatment: "Pain Cure & Affordable Therapy",
    rating: 5,
    review: "Good practice and decent coverage and affordable price and treatment better iam cure my pain thanks dr.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 80,
    source: "google",
    reviewDate: "2 Jun 2024",
    createdAt: "2024-06-02T10:00:00.000Z",
  },
  {
    id: "g-rev-81",
    patientName: "Shibly Meeran",
    treatment: "Recurrent Lumbar Back Pain & Traction",
    rating: 5,
    review: "She’s one of the best physiotherapist around. I had gotten treatment for back pain from her 7-8 months back and got completely relieved. However recently got it back again after moving to Bengaluru. The pain did not get reduced even after visiting a physiotherapist there. Planned a trip to Chennai and visited her and came for a few sessions. Now I’m completely alright and back on foot. Dr. Sundaravalli understands the underlying problem and suggests the right treatment.",
    location: "Bengaluru / Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 81,
    source: "google",
    reviewDate: "26 Apr 2024",
    createdAt: "2024-04-26T10:00:00.000Z",
  },
  {
    id: "g-rev-82",
    patientName: "deepak edss",
    treatment: "Cervical & Lumbar Disc Tightness (Relief Day 4)",
    rating: 5,
    review: "I am deepak visited G.G physiotherapic clinic for cervical and lumbar disc pain. I got relief from the 4th day of the treatment and my tightness has been relieved. Thank you for the care and the treatment and recommend for pain relieving treatment..",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 82,
    source: "google",
    reviewDate: "26 Apr 2024",
    createdAt: "2024-04-26T10:00:00.000Z",
  },
  {
    id: "g-rev-83",
    patientName: "Srinath Srinivasan",
    treatment: "Ongoing Pain Management & Assessment",
    rating: 5,
    review: "I have been visiting the clinic few times in the last couple of months now. Sundaravalli mam is very knowledgeable and experienced physio professional. She greatly helps with the much needed pain management by identifying the issue and the course of action. Highly recommended place for pain management and physio.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 83,
    source: "google",
    reviewDate: "23 Apr 2024",
    createdAt: "2024-04-23T10:00:00.000Z",
  },
  {
    id: "g-rev-84",
    patientName: "gayathri devi",
    treatment: "Lower Back Pain & Step-by-Step Rehabilitation",
    rating: 5,
    review: "Sundravalli madam is expert in diagnosing patients. She treated me for lower back pain and gave me step by step treatment for relieving pain. Finally she taught all the necessary exercises that will make my day today routine better. I recommended her for all physio issues which can be treated with utmost care.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 84,
    source: "google",
    reviewDate: "5 Apr 2024",
    createdAt: "2024-04-05T10:00:00.000Z",
  },
  {
    id: "g-rev-85",
    patientName: "abyaya mishra",
    treatment: "Accurate Diagnosis & Fast Pain Relief",
    rating: 5,
    review: "Doctor diagnosed the problem very well and gave quick pain relief. Very satisfied with the outcome.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 85,
    source: "google",
    reviewDate: "1 Apr 2024",
    createdAt: "2024-04-01T10:00:00.000Z",
  },
  {
    id: "g-rev-86",
    patientName: "vijay kumar",
    treatment: "Persistent Multi-Month Thumb & Joint Pain",
    rating: 5,
    review: "Very happy and satisfying and most importantly relieving experience from the persistent thumb pain that I was suffering since many months. Doctor is the best for physiotherapy and I would highly recommend people suffering from any physio related issues to attend and you will not only get relieved of the pain but also you will receive earnest suggestions.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 86,
    source: "google",
    reviewDate: "26 Mar 2024",
    createdAt: "2024-03-26T10:00:00.000Z",
  },
  {
    id: "g-rev-87",
    patientName: "Rukmini haran",
    treatment: "Neck, Hip Pain & Flat Foot Management",
    rating: 5,
    review: "She is accurate in diagnosis and treatment. Affordable, friendly and teaches stretches which can be done later. Thank you so much for relieving pain and giving a good treatment for neck pain, hip pain, flat foot issues.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 87,
    source: "google",
    reviewDate: "23 Mar 2024",
    createdAt: "2024-03-23T10:00:00.000Z",
  },
  {
    id: "g-rev-88",
    patientName: "M N",
    treatment: "Comprehensive Orthopedic Diagnosis",
    rating: 5,
    review: "Today, I am writing this review based on my own treatment experience at this clinic. Dr.Sundravalli is very well knowledged and is very calm and polite with her patients, the diagnosis what she tells us is very apt to our condition and she provides the best physiotherapy treatment and I highly recommend her for all your physiotherapy related problems, Thank you doctor.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 88,
    source: "google",
    reviewDate: "3 Mar 2024",
    createdAt: "2024-03-03T10:00:00.000Z",
  },
  {
    id: "g-rev-89",
    patientName: "Uppili Srinivasan",
    treatment: "Best Physio in Perungudi with Follow-Up",
    rating: 5,
    review: "I had a fantastic treatment & good follow up from the Doctor. This is the best physiotherapy clinic in perungudi with affordable fees & I will truly recommend to my friends. Keep up your good job doctor. Thanks for all your help. Best regards.",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 89,
    source: "google",
    reviewDate: "2 Mar 2024",
    createdAt: "2024-03-02T10:00:00.000Z",
  },
  {
    id: "g-rev-90",
    patientName: "Dipa Parkhe",
    treatment: "Total Recovery & Supportive Care",
    rating: 5,
    review: "Doctor is very kind and supportive she give me a very Good Treatment and now I am totally recover. Thank you Doctor. You are the Best..",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 90,
    source: "google",
    reviewDate: "2 Mar 2024",
    createdAt: "2024-03-02T10:00:00.000Z",
  },
  {
    id: "g-rev-91",
    patientName: "Ramkumar Jayakumar",
    treatment: "Advanced Equipment & Genuine Guidance",
    rating: 5,
    review: "Best physiotherapy care with state of the art equipment and genuine guidance for long term joint health.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 91,
    source: "google",
    reviewDate: "31 Dec 2023",
    createdAt: "2023-12-31T10:00:00.000Z",
  },
  {
    id: "g-rev-92",
    patientName: "Syed",
    treatment: "Chronic Knee & Back Pain",
    rating: 5,
    review: "Very good results for chronic knee and back pain. Doctor is very polite, understanding, and attentive to symptoms.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 92,
    source: "google",
    reviewDate: "30 Nov 2023",
    createdAt: "2023-11-30T10:00:00.000Z",
  },
  {
    id: "g-rev-93",
    patientName: "Parvathi Vijaykumar",
    treatment: "Sustained Pain Relief & Guided Exercises",
    rating: 5,
    review: "Very attentive doctor. Guided me through exercises that gave sustained relief from joint tightness.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 93,
    source: "google",
    reviewDate: "9 Nov 2023",
    createdAt: "2023-11-09T10:00:00.000Z",
  },
  {
    id: "g-rev-94",
    patientName: "aslam ibrahim",
    treatment: "10-15 Years Chronic Cervical & Lumbar Pain (PEMF Therapy)",
    rating: 5,
    review: "Over 10-15years I have cervical and lumbar pain .when I went to this physiotherapy clinic after doctor consult, now I am better. PEMF therapy is good to decrease our nervepain indepth. She is caring and understand the patients pain and treated.",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 94,
    source: "google",
    reviewDate: "19 Oct 2023",
    createdAt: "2023-10-19T10:00:00.000Z",
  },
  {
    id: "g-rev-95",
    patientName: "Lalith Kumar",
    treatment: "Clear Guidance & Support",
    rating: 5,
    review: "Caring and Knowledgeable physio practioner. Provided clear guidance and support for my rehabilitation.",
    location: "Chennai",
    isLocalGuide: true,
    featured: false,
    published: true,
    displayOrder: 95,
    source: "google",
    reviewDate: "18 Oct 2023",
    createdAt: "2023-10-18T10:00:00.000Z",
  },
  {
    id: "g-rev-96",
    patientName: "Teo Nathanael",
    treatment: "Pediatric Radial Nerve Injury & PEMF Therapy (Avoided Surgery)",
    rating: 5,
    review: "I took my 8 year old son for treatment of radial nerve and posterior interosseous nerve damage. His nerve was damaged due to a supracondylar fracture. Dr. Sundaravalli treated with PEMF (pulsed electromagnetic field) therapy. It helped him to recover well in 6 weeks. From having very minimal extension in fingers and thumb, he obtained full extension. We were able to avoid open surgery for treating the nerve damage. We accompanied strength exercise along with treatment to get quicker and better result.",
    location: "Chennai",
    isLocalGuide: true,
    featured: true,
    published: true,
    displayOrder: 96,
    source: "google",
    reviewDate: "8 Oct 2023",
    createdAt: "2023-10-08T10:00:00.000Z",
  },
  {
    id: "g-rev-97",
    patientName: "Ramachandra Gupta Vinnakota",
    treatment: "Exceptional Clinical Diagnosis & Stiffness Care",
    rating: 5,
    review: "Exceptional doctor with deep clinical knowledge. My stiffness has completely disappeared through her structured therapy sessions.",
    location: "Chennai",
    featured: false,
    published: true,
    displayOrder: 97,
    source: "google",
    reviewDate: "6 Oct 2023",
    createdAt: "2023-10-06T10:00:00.000Z",
  },
  {
    id: "g-rev-98",
    patientName: "Sadhu Sundar",
    treatment: "ICT, IFT, Ultrasound & Novel Dry Needling",
    rating: 5,
    review: "My wife was having pain in neck, in right shoulder and in right hand for the past 30 days. As she was suggested ICT and IFT, Dr.Sundravalli, GG physcio centre had given these procedures. The very first day after the procedures my wife could feel the relief. From 4th day Dr.Sundravalli had introduced another procedure in addition to the ICT, IFT, through ultrasound. On the last day Dr.Sundravalli had concluded the sessions with a novel therapy program by Needle puncture to avoid the relapse and suggested physical exercises to do in home. My wife is totally alright from the bothering pain. The fee collected was so economical in addition to Dr.Sundravalli's kind and dedicated care. We recommend all the people who are suffering like my wife to avail Dr.Sundravalli's best service. Long live to serve the needy Dr.Sundravalli.",
    location: "Perungudi, Chennai",
    featured: true,
    published: true,
    displayOrder: 98,
    source: "google",
    reviewDate: "25 Sept 2023",
    createdAt: "2023-09-25T10:00:00.000Z",
  },
  {
    id: "g-rev-99",
    patientName: "NL J",
    treatment: "Cervical & Lumbar Spondylosis (Results from Day 1)",
    rating: 5,
    review: "HIIGHLY RECOMMENDED... Diagnosed with cervical and lumbar spondylosis. On Doctors advise visited for prescribed exercises. But after analysing the issue, clarified in detail on the problem and suggested physiotherapy and then exercises... After the physio sessions I felt much better. CAN SEE THE RESULTS FROM DAY ONE. At the end of the duration, she told the exercises which im working on. Thank you Dr. Sundaravalli 😊",
    location: "Chennai",
    featured: true,
    published: true,
    displayOrder: 99,
    source: "google",
    reviewDate: "4 Sept 2023",
    createdAt: "2023-09-04T10:00:00.000Z",
  },
];
